### ISSUE TITLE
Abandoned package league/url

### ISSUE THREAD

**Issue by mdeboer** [g3i/lxHive#227]
When running `composer install` you get a warning:
`Package league/url is abandoned, you should avoid using it. Use league/uri instead.`

Not sure but it sounds like a minor change 😃

**Comment by RoboSparrow** [comment]
Hi Martin, yes this is **definitely** on our TODOS (#181), 
However, the replacement is not that easy as the current package is deeply intervened with several modules. This would be a breaking change.

The replacement library, https://github.com/thephpleague/uri requires minimum PHP 7 and plus `intl` and `mbsting` extension, whereas we still support PHP 5.5.x

>PHP >= 7.0.13 but the latest stable version of PHP is recommended
>the mbstring extension
>the intl extension

Our discussion was to use neither of these libraries and just use [PHP core url parsing](http://php.net/manual/en/function.parse-url.php), as part of a general process of uncluttering and simplification. However, this requires considering exotic use cases and some thorough testing.

lxHive has been quiet for the last year and it is time to initiate the next milestone!
