### ISSUE TITLE
Default expiry time is incorrect for temporary access tokens

### ISSUE THREAD

**Issue by mdeboer** [g3i/lxHive#228]
The documentation on temporary access tokens states that the default expiry time is set to 3600 seconds (1 hour). This is not true as it's set to null by default when the parameter has been omitted from the request.

See https://github.com/Brightcookie/lxHive/blob/master/src/xAPI/Service/Auth/Basic.php#L168

**Comment by RoboSparrow** [comment]
Thanks for picking this up. I corrected the wiki for now. The real fix, however, is to set the default 1h period programmatically with the next version bump.
